import React from 'react'
import Container from 'react-bootstrap/Container';
import Head from 'next/head'
import CustomNavbar from "../components/CustomNavbar";




export default function ComingSoon() {

    return (
      <>
        <Head>
          <title>NatureDAO - Landing Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossOrigin="anonymous"
          />
        </Head>
        <div className="mainWindow2">
          <CustomNavbar/>
          <div className="middleRow2">
            <h1>
              <strong>COMING SOON</strong>
            </h1>
          </div>
        </div>
      </>
    );
}